# RedHat related OSs
- name: Yum install {{ item }}
  action: yum pkg={{ item }} state=installed
  when: "ansible_os_family == 'RedHat'"
  with_items:
  - wget
  - tar
  - gzip
  - java-1.7.0-openjdk

# Debian related OSs
- name: Apt install {{ item }}
  action: apt pkg={{ item }} state=installed update_cache=yes cache_valid_time=604800
  when: "ansible_os_family == 'Debian'"
  with_items:
  - wget
  - tar
  - gzip
  - openjdk-7-jre-headless

- get_url: url={{ hadoop_mirrors|random }}/hadoop-{{ hadoop_version }}.tar.gz dest=/tmp/hadoop-{{ hadoop_version }}.tar.gz

- unarchive: src=/tmp/hadoop-{{ hadoop_version }}.tar.gz dest=/opt creates=/opt/hadoop-2.7.2

- file: dest={{ hadoop_home }} src=/opt/hadoop-{{ hadoop_version }} state=link

- file: dest=/opt/hadoop src={{ hadoop_home }} state=link

- lineinfile: dest="{{ hadoop_home }}/etc/hadoop/hadoop-env.sh" regexp=JAVA_HOME= line="export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64"
  when: "ansible_os_family == 'Debian'"

- lineinfile: dest="{{ hadoop_home }}/etc/hadoop/hadoop-env.sh" regexp=JAVA_HOME= line="export JAVA_HOME=/usr/lib/jvm/jre-1.7.0"
  when: "ansible_os_family == 'RedHat'"

- template: src=yarn-site.xml dest="{{ hadoop_home }}/etc/hadoop/yarn-site.xml" owner=root group=root
  notify:
   - restart hadoop-dfs
   - restart yarn-resourcemanager
   - restart hadoop-datanode
   - restart yarn-nodemanager

- template: src=core-site.xml dest="{{ hadoop_home }}/etc/hadoop/core-site.xml" owner=root group=root
  notify:
   - restart hadoop-dfs
   - restart yarn-resourcemanager
   - restart hadoop-datanode
   - restart yarn-nodemanager

- template: src=slaves dest="{{ hadoop_home }}/etc/hadoop/slaves" owner=root group=root
  notify:
   - refreshDFSNodes
   - refreshYarnNodes
   - restart hadoop-datanode
   - restart yarn-nodemanager

- command: "{{ hadoop_home }}/bin/hdfs namenode -format creates=/tmp/hadoop-root/dfs/name"
  when: "hadoop_type_of_node == 'master'"

- name: Open port {{item}} - tcp in the firewall
  command: iptables -I INPUT -p tcp --dport {{item}}:{{item}} -j ACCEPT
  ignore_errors: yes
  with_items:
  - 8088
  - 50030

- name: Open all ports from ip {{ item.1 }} in the firewall
  command: iptables -I INPUT -p tcp -s {{ item.1 }}  -j ACCEPT
  ignore_errors: yes
  with_together:
      - groups.all
      - ansible_all_ipv4_addresses

- name: save iptables
  shell: iptables-save > /etc/sysconfig/iptables
  when: "ansible_os_family == 'RedHat'"

